### ISSUE TITLE
NDPIReader & makeRGBImage last scanlines wrong

### ISSUE THREAD

**Issue by mstritt** [ome/bioformats#3059]
When using NDPIReader and converting the data to an image using a BufferdImageReader - or makeRGBImage directly - on some images (probably depending on the height) the last few pixel rows (always 8?) have value 128 instead of the correct pixel value.

The problem can be reproduced on the example image
http://downloads.openmicroscopy.org/images/Hamamatsu-NDPI/manuel/test3-FITC%202%20(485).ndpi

Code:

```
import loci.formats.FormatReader;
import loci.formats.gui.AWTImageTools;
import loci.formats.in.NDPIReader;
import java.awt.image.BufferedImage;

public class TestNDPIReader {
    public static void main(String[] args) {
        // image from http://downloads.openmicroscopy.org/images/Hamamatsu-NDPI/manuel/test3-FITC%202%20(485).ndpi
        String filename = "test3-FITC 2 (485).ndpi";
        try (FormatReader r = new NDPIReader()) {
            r.setId(filename);
            byte[] bytes = r.openBytes(0);
            int last = bytes[bytes.length-1] & 0xf;   // here the last byte (blue value) is 0, which is correct
            System.out.println(last);    // 0
            // openImage results in value 128 - which is wrong. Trace down to makeRGBImage...
           // BufferedImage bi = AWTImageTools.openImage(bytes,r,r.getSizeX(),r.getSizeY());
           // BufferedImage bi = AWTImageTools.makeImage(bytes, r.getSizeX(), r.getSizeY(), 3, true, 1, false, true, false);
            BufferedImage bi = AWTImageTools.makeRGBImage(bytes, 3, r.getSizeX(), r.getSizeY(), true);
            int lastBi = bi.getRaster().getSample(bi.getWidth()-1,bi.getHeight()-1,0);
            System.out.println(lastBi);  // 128 but should be 0
            // this problem holds for the last 8 scanline pixels (samples width*(height-1..8)*3), before it's correct
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```
Maybe this is related to [#875](https://github.com/openmicroscopy/bioformats/issues/875) and/or [#836](https://github.com/openmicroscopy/bioformats/pull/836)

Result of the image using a BufferedImageReader (you can see the last part (8 lines) is gray)
![testndpi](https://user-images.githubusercontent.com/5435937/35679912-fe59e0dc-0758-11e8-8f6d-adf1e501148d.jpg)
Zoomin:
![testndpi-zoom](https://user-images.githubusercontent.com/5435937/35679942-1c5d0794-0759-11e8-99e8-263b1da0ff50.jpg)

**Comment by dgault** [comment]
Hi @mstritt, thank you for reporting this issue. I was able to reproduce the behaviour using the first series of the sample file at http://downloads.openmicroscopy.org/images/Hamamatsu-NDPI/manuel/test3-FITC%202%20(485).ndpi as you suggested. From my initial investigation the problem appears to lie within the NDPIReader itself rather than the AWTImageTools functions. This will require further investigation on our side before a fix can be put in place.

**Comment by melissalinkert** [comment]
Confirmed that this is still a problem with #3505 included.

**Comment by jfkotw** [comment]
I just tested the fix while preparing the latest release of Orbit Image Analysis which uses Bioformats 6.4.0, and it appears that the issue is still present. I verified this by running the same code that @mstritt submitted at the top of this bug report.

**Comment by jfkotw** [comment]
FYI: I pushed the code including the gradle configuration to a repo here: https://github.com/jfkotw/LargeNDPIBug/blob/master/src/main/java/Issue3059.java

**Comment by melissalinkert** [comment]
6.4.0 does not contain the fix for this issue, so it is completely expected that you will still see the problem when using 6.4.0.
